Select * from "PD_SVOC_CONFORMED"."SVOC"."PERSON" ;

Select FIRST_NAME,LAST_NAME from "PD_SVOC_CONFORMED"."SVOC"."PERSON" ;

Select SOURCE_SYSTEM,DOB,LAST_NAME from "PD_SVOC_CONFORMED"."SVOC"."PERSON" limit 10;

Select max(EXTRACT_TS) from "PD_SVOC_CONFORMED"."SVOC"."PERSON" ;

Select min(EXTRACT_TS) from "PD_SVOC_CONFORMED"."SVOC"."PERSON" ;

select EXTRACT_TS from "PD_SVOC_CONFORMED"."SVOC"."PERSON" where EXTRACT_TS LIKE '2022-09-18%' limit 10 ;

select EXTRACT_TS from "PD_SVOC_CONFORMED"."SVOC"."PERSON" where EXTRACT_TS LIKE '2022-09-17%' or EXTRACT_TS LIKE '2022-09-18%' ;

SELECT DISTINCT SOURCE_SYSTEM from "PD_SVOC_CONFORMED"."SVOC"."PERSON" ;

select count (*) from "PD_SVOC_CONFORMED"."SVOC"."PERSON"  ;

select * from "PD_SVOC_CONFORMED"."SVOC"."PERSON"  where SOURCE_SYSTEM = 'MSI_CLIENT' and FIRST_NAME = 'John' and EXTRACT_TS = '2022-05-06' limit 100 ;

select DISTINCT SOURCE_SYSTEM, count (SOURCE_SYSTEM) from "PD_SVOC_CONFORMED"."SVOC"."PERSON" GROUP BY SOURCE_SYSTEM ;

select EXTRACT_TS from "PD_SVOC_CONFORMED"."SVOC"."PERSON" ORDER BY EXTRACT_TS DESC ;

select DISTINCT SOURCE_SYSTEM, count (SOURCE_SYSTEM) as "Counts" from "PD_SVOC_CONFORMED"."SVOC"."PERSON" GROUP BY SOURCE_SYSTEM ORDER BY "Counts" DESC 

Select * from "PD_SVOC_CONFORMED"."SVOC"."PERSON" where DOB IS NULL ;

Select * from "PD_SVOC_CONFORMED"."SVOC"."PERSON" where DOB IS NOT NULL ;

Select LEN (FIRST_NAME) from "PD_SVOC_CONFORMED"."SVOC"."PERSON" ;

select DISTINCT SOURCE_SYSTEM, count (*) as "NEW" from "PD_SVOC_CONFORMED"."SVOC"."PERSON" GROUP BY SOURCE_SYSTEM HAVING COUNT(*)>100000000 ;

SELECT P.FIRST_NAME, P.LAST_NAME, PHP.TYPE , PO.POLICY_NUMBER FROM PD_SVOC_CONFORMED.SVOC.PERSON P
INNER JOIN POLICY_HAS_POLICYHOLDER_PERSON PHP INNER JOIN PD_SVOC_CONFORMED.SVOC.POLICY PO
WHERE P.ID=PHP.DST and PHP.SRC=PO.ID and TYPE = 'NIN' limit 10 ;


SELECT P.FIRST_NAME, P.LAST_NAME, P.SOURCE_SYSTEM,  PO.POLICY_NUMBER, PHP.TYPE , P.SOURCE_SYSTEM FROM PD_SVOC_CONFORMED.SVOC.PERSON P
INNER JOIN POLICY_HAS_POLICYHOLDER_PERSON PHP INNER JOIN PD_SVOC_CONFORMED.SVOC.POLICY PO 
WHERE P.ID=PHP.DST and PHP.SRC=PO.ID and TYPE ='NIN' and POLICY_NUMBER = '14627960' and SOURCE_SYSTEM = 'MSI_CLIENT' limit 10 ;


SELECT P.FIRST_NAME as FIRSTNAME, P.LAST_NAME as LASTNAME, PO.POLICY_NUMBER as POLICYNUMBER, PO.ID FROM PD_SVOC_CONFORMED.SVOC.PERSON P
INNER JOIN POLICY_HAS_POLICYHOLDER_PERSON PHP INNER JOIN PD_SVOC_CONFORMED.SVOC.POLICY PO
WHERE NOT PHP.SRC=PO.ID and FIRSTNAME IS NULL and LASTNAME IS NULL limit 10 ;